### ISSUE TITLE
Створити CRUD для фото

### ISSUE THREAD

**Issue by SergiiTernytskyi** [SergeySudaraenko/TeamProject#3]
1.Користувачі можуть завантажувати світлини з описом (POST).
2.Користувачі можуть видаляти світлини (DELETE).
3.Користувачі можуть редагувати опис світлини (PUT).
4.Користувачі можуть отримувати світлину за унікальним посиланням (GET).

**Comment by TKobzar777** [comment]
Взяла в роботу
