### ISSUE TITLE
Створити CRUD для коментарів

### ISSUE THREAD

**Issue by SergiiTernytskyi** [SergeySudaraenko/TeamProject#7]
Під кожною світлиною, є блок з коментарями. Користувачі можуть коментувати світлину один одного
Користувач може редагувати свій коментар, але не видаляти
Адміністратори та модератори можуть видаляти коментарі.
Для коментарів обов'язково зберігати час створення та час редагування коментаря в базі даних.

**Comment by TKobzar777** [comment]
123
